name: gadget
favicon: null
layout_spectrum: 1
typography_spectrum: 0.5344084531534463
title: 'Gadgets, Gadgets, Gadgets'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#808080'
    - '#804000'
    - '#000000'
    - '#ffffff'
    - '#aaaaaa'
  brandStrength: 0.25
  lightness: 0.5625
  saturation: 0.0625
  rhythmicContrast: 0.18485778057947755
purpose: []
